### PR TITLE
- Add Support Video only

### PR DESCRIPTION
**Pull request by kaquay**
- Update Example

### CODE REVIEW

**Review by pesjak — COMMENTED** [review]
Nice 👍

**Comment by kaquay** [comment]
> Nice 👍

seems this lib no longer support

**Comment by akshay2211** [comment]
Hello @kaquay,
This library is being rewritten completely in kotlin, with CameraX and scope storage feature, including many minor features with more optimized functionality.
It will be released soon with Video Only Support as well.
Thank you for your effort.

**Comment by kaquay** [comment]
> Hello @kaquay,
> This library is being rewritten completely in kotlin, with CameraX and scope storage feature, including many minor features with more optimized functionality.
> It will be released soon with Video Only Support as well.
> Thank you for your effort.

Hi @akshay2211
Sounds great!

**Pull request merged**
